eureka:
  instance:
    hostname: localhost
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/

# prevent from own yml files overriding system properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9099/realms/ecommerce"
  cloud:
    config:
      override.system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG