# Customer Service Configurations
spring:
  data:
    mongodb:
      username: vena
      password: vena
      additional-hosts: localhost
      port: 27017
      database: customer
      authentication-database: admin


server:
  port: 8090