# Payment Service Configurations
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: update
    database: postgresql
    database-platform:  org.hibernate.dialect.PostgreSQLDialect

  # Payment Kafka Configuration
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.vena.ecommerce.notification.PaymentNotificationRequest
server:
  port: 8060