#gateway-service-docker.yml
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/ecommerce"
          jwk-set-uri: "http://keycloak:8080/realms/ecommerce/protocol/openid-connect/certs"